name: Add issue to Team MAS project
on:
  issues:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to GitHub Project
        uses: actions/add-to-project@v0.4.0
        with:
          project-url: "https://github.com/orgs/DAKISpro/projects/1"
          github-token: ${{ secrets.ACTION_TOKEN }}
