name: Add pr to the Dakis project
on:
  pull_request:
    types:
      - opened
jobs:
  add-to-project:
    name: Add pr to project
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/DAKISpro/projects/1
          github-token: ${{ secrets.GH_PROJECT_TOKEN }}
 
