name: Release and build and push to registry optionally publish to pypi
on:
  workflow_call:
    inputs:
      push_docker:
        description: "Whether to build and push Docker images"
        required: false
        type: boolean
        default: true
      publish_pypi:
        description: "Whether to build and publish the Python package"
        required: false
        type: boolean
        default: false
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      # Build + publish Python package to TestPyPI on release
      - name: Checkout
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
        if: ${{ steps.release.outputs.release_created && inputs.publish_pypi }}
      - name: Build Python distribution
        run: |
          python -m pip install --upgrade pip build
          python -m build
        if: ${{ steps.release.outputs.release_created && inputs.publish_pypi }}
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        if: ${{ steps.release.outputs.release_created && inputs.publish_pypi }}
      # Docker steps (optional)
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: zalfrpm
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created && inputs.push_docker }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: ${{ steps.release.outputs.release_created && inputs.push_docker }}
      - name: Build and push
        uses: docker/bake-action@v6
        with:
          push: true
        env:
          TAG: ${{ steps.release.outputs.version }}
        if: ${{ steps.release.outputs.release_created && inputs.push_docker }}
