name: Release and build and push to registry
on:
  workflow_call:
    inputs:
      push_docker:
        description: Build and push Docker images
        required: false
        type: boolean
        default: true
      dockerhub_username:
        description: Docker Hub username
        required: false
        type: string
        default: zalfrpm
    secrets:
      DOCKERHUB_TOKEN:
        description: Docker Hub token or password
        required: true
    outputs:
      release_created:
        description: Whether a release was created
        value: ${{ jobs.release-please.outputs.release_created }}
      version:
        description: Created release version
        value: ${{ jobs.release-please.outputs.version }}
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.version }}
  docker-release:
    name: Build and push Docker image
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' && inputs.push_docker }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/bake-action@v6
        with:
          push: true
        env:
          TAG: ${{ needs.release-please.outputs.version }}
