name: Release and build and push to registry

on:
  workflow_call:
    inputs:
      release-type:
        description: "The release type to use (python, node etc)"
        default: "simple"
        type: string
        required: false

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: ${{inputs.release-type}}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: zalfrpm
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: ${{ steps.release.outputs.release_created }}
      - name: Build and push
        uses: docker/bake-action@v6
        with:
          push: true
        env:
          TAG: ${{ steps.release.outputs.version }}
        if: ${{ steps.release.outputs.release_created }}
