name: Release and build and push to registry optionally publish to pypi
on:
  workflow_call:
    inputs:
      push_docker:
        description: "Whether to build and push Docker images"
        required: false
        type: boolean
        default: true
    outputs:
      release_created:
        description: Whether a release was created
        value: ${{ jobs.release-please.outputs.release_created }}
      
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      # Docker steps (optional)
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: zalfrpm
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created && inputs.push_docker }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: ${{ steps.release.outputs.release_created && inputs.push_docker }}
      - name: Build and push
        uses: docker/bake-action@v6
        with:
          push: true
        env:
          TAG: ${{ steps.release.outputs.version }}
        if: ${{ steps.release.outputs.release_created && inputs.push_docker }}
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
